const srvList = [
	{
		name: 'Synerex Server',
		label: 'SxSrv',
		status: 'debug-stop',
		item: null,
		cmd: 'synerexClient.startSynerex',
		stopping: false,
		updating: false,
		task: null,
		type: 'synerexClient.synerexServer',
		repo: 'synerex_server',
		binary: 'synerex-server',
		port: 10000,
	},
	{
		name: 'Node Server',
		label: 'NodeSrv',
		status: 'debug-stop',
		item: null,
		cmd: 'synerexClient.startNode',
		stopping: false,
		updating: false,
		task: null,
		type: 'synerexClient.nodeServer',
		repo: 'synerex_nodeserv',
		binary: 'nodeserv',
		port: 9990,
	},
	{
		name: 'Proxy Provider',
		label: 'ProxyPrv',
		status: 'debug-stop',
		item: null,
		cmd: 'synerexClient.startProxyPrv',
		stopping: false,
		updating: false,
		task: null,
		type: 'synerexClient.proxyProvider',
		repo: 'provider_proxy',
		binary: 'proxy',
		port: 18000,
	},
	{
		name: 'Harmoware-VIS Layers Provider',
		label: 'HVLPrv',
		status: 'debug-stop',
		item: null,
		cmd: 'synerexClient.startHVLPrv',
		stopping: false,
		updating: false,
		task: null,
		type: 'synerexClient.harmovisLayersProvider',
		repo: 'provider_harmovis_layers',
		binary: 'harmovis-layers',
		port: 10080,
	},
];

module.exports = {
    srvList,
}
