const sxClient = 'synerexClient';

const srvList = [
	{
		name: 'Synerex Server',
		label: 'SxSrv',
		status: 'debug-stop',
		item: null,
		cmd: `${sxClient}.startSynerex`,
		stopping: false,
		updating: false,
		task: null,
		type: 'synerexServer',
		repo: 'synerex_server',
		binary: 'synerex-server',
		port: 10000,
	},
	{
		name: 'Node Server',
		label: 'NodeSrv',
		status: 'debug-stop',
		item: null,
		cmd: `${sxClient}.startNode`,
		stopping: false,
		updating: false,
		task: null,
		type: 'nodeServer',
		repo: 'synerex_nodeserv',
		binary: 'nodeserv',
		port: 9990,
	},
	{
		name: 'Proxy Provider',
		label: 'ProxyPrv',
		status: 'debug-stop',
		item: null,
		cmd: `${sxClient}.startProxyPrv`,
		stopping: false,
		updating: false,
		task: null,
		type: 'proxyProvider',
		repo: 'provider_proxy',
		binary: 'proxy',
		port: 18000,
	},
	{
		name: 'Harmoware-VIS Layers Provider',
		label: 'HVLPrv',
		status: 'debug-stop',
		item: null,
		cmd: `${sxClient}.startHVLPrv`,
		stopping: false,
		updating: false,
		task: null,
		type: 'harmovisLayersProvider',
		repo: 'provider_harmovis_layers',
		binary: 'harmovis-layers',
		port: 10080,
	},
];

module.exports = {
	sxClient,
    srvList,
}
